# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayarlar(object):
    def setupUi(self, Ayarlar):
        Ayarlar.setObjectName("Ayarlar")
        Ayarlar.resize(310, 190)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ayarlar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Ayarlar)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame.setStyleSheet("#frame{\n"
"background-color:rgb(52,52,52);\n"
"border-radius:16px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(-1, 0, 5, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(250, 35))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color:rgb(25, 25, 25);\n"
"border-radius:15px\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("#label{\n"
"    font: 15pt \"Ubuntu Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Ayarlar)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(52, 52, 52);\n"
"border-radius:15px\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setStyleSheet("#groupBox{\n"
"color:white;\n"
"\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(40, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TRY = QtWidgets.QRadioButton(self.groupBox)
        self.TRY.setStyleSheet("#TRY{\n"
"color:white;\n"
"}")
        self.TRY.setChecked(True)
        self.TRY.setObjectName("TRY")
        self.horizontalLayout.addWidget(self.TRY)
        self.USD = QtWidgets.QRadioButton(self.groupBox)
        self.USD.setStyleSheet("#USD{\n"
"color:white;\n"
"}")
        self.USD.setObjectName("USD")
        self.horizontalLayout.addWidget(self.USD)
        self.EUR = QtWidgets.QRadioButton(self.groupBox)
        self.EUR.setStyleSheet("#EUR{\n"
"color:white;\n"
"}")
        self.EUR.setObjectName("EUR")
        self.horizontalLayout.addWidget(self.EUR)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton.setMaximumSize(QtCore.QSize(48, 48))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_2.setMaximumSize(QtCore.QSize(48, 48))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Ayarlar)
        QtCore.QMetaObject.connectSlotsByName(Ayarlar)

    def retranslateUi(self, Ayarlar):
        _translate = QtCore.QCoreApplication.translate
        Ayarlar.setWindowTitle(_translate("Ayarlar", "Ayarlar"))
        self.label.setText(_translate("Ayarlar", "AYARLAR"))
        self.groupBox.setTitle(_translate("Ayarlar", "Para Birimleri"))
        self.TRY.setText(_translate("Ayarlar", "TRY"))
        self.USD.setText(_translate("Ayarlar", "USD"))
        self.EUR.setText(_translate("Ayarlar", "EUR"))
